services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - be-db-network
    ports:
      - '5432:5432'

  cache:
    image: redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass redis
    networks:
      - be-db-network
    ports:
      - '6379:6379'

  backend:
    depends_on:
      - database
      - cache
    build:
      context: ./backend
    container_name: backend
    env_file:
      - ./backend/.env.development
    ports:
      - '1337:1337'
    volumes:
      - ./backend/.:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    networks:
      - be-db-network
      - be-fe-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env.development
    ports:
      - '5173:5173'
    volumes:
      - ./frontend/.:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host
    networks:
      - be-fe-network

networks:
  be-db-network:
    driver: bridge
  be-fe-network:
    driver: bridge
